export const certificates = [
  {
    id: 1,
    title: "Excelencia Académica",
    academy: "IUTEPAL",
    date: "09-06-2023",
    image: "/certificates/IUTEPAL.JPG",
    importance: "rated",
  },
  {
    id: 2,
    title: "Máster Completo en Java",
    academy: "Udemy - Andrés Guzmán",
    date: "18-07-2023",
    image: "/certificates/MasterJavaUdemy.jpg",
    importance: "rated",
  },
  {
    id: 3,
    title: "Next.js 14",
    academy: "Platzi",
    date: "10-03-2025",
    image: "/certificates/next.js.png",
    importance: "rated",
  },
  {
    id: 4,
    title: "Fundamentos de JavaScript",
    academy: "Platzi",
    date: "04-07-2025",
    image: "/certificates/FundamentosJS.png",
    importance: "basic",
  },
  {
    id: 5,
    title: "JavaScript: Manipulación del DOM",
    academy: "Platzi",
    date: "10-07-2025",
    image: "/certificates/ManipulacionDOM.png",
    importance: "medium",
  },
  {
    id: 6,
    title: "Discord: Comuniación para Comunidades",
    academy: "Platzi",
    date: "11-07-2025",
    image: "/certificates/Discord.png",
    importance: "basic",
  },
  {
    id: 7,
    title: "Patrones de Diseño Creacionales en JavaScript",
    academy: "Platzi",
    date: "19-07-2025",
    image: "/certificates/PatronesDiseñoJS.png",
    importance: "medium",
  },
  {
    id: 8,
    title: "Introducción a la Web: Historia y Funcionamiento de Internet",
    academy: "Platzi",
    date: "21-07-2025",
    image: "/certificates/IntroduccionWeb.png",
    importance: "basic",
  },
  {
    id: 9,
    title: "JavaScript Engine (V8) y el Navegador",
    academy: "Backend Masters",
    date: "23-07-2025",
    image: "/certificates/JSEngineV8.png",
    importance: "medium",
  },
  {
    id: 10,
    title: "ECMAScript: Historia y Versiones de JavaScript",
    academy: "Platzi",
    date: "06-08-2025",
    image: "/certificates/ECMAScript.png",
    importance: "medium",
  },
  {
    id: 11,
    title: "Cybersecurity Basics",
    academy: "Security Academy",
    date: "2022",
    image: "/placeholder.svg?height=200&width=300",
    importance: "sencillo",
  },
];
