export const certificates = [
  {
    id: 1,
    title: "Full Stack Development",
    academy: "Tech Academy",
    date: "2024",
    image: "/placeholder.svg?height=200&width=300",
    importance: "destacado",
  },
  {
    id: 2,
    title: "React Advanced Patterns",
    academy: "React Institute",
    date: "2023",
    image: "/placeholder.svg?height=200&width=300",
    importance: "complejo",
  },
  {
    id: 3,
    title: "JavaScript Fundamentals",
    academy: "Code School",
    date: "2023",
    image: "/placeholder.svg?height=200&width=300",
    importance: "intermedio",
  },
  {
    id: 4,
    title: "Git & GitHub",
    academy: "Version Control Academy",
    date: "2022",
    image: "/placeholder.svg?height=200&width=300",
    importance: "sencillo",
  },
  {
    id: 5,
    title: "Database Design",
    academy: "Data Institute",
    date: "2023",
    image: "/placeholder.svg?height=200&width=300",
    importance: "complejo",
  },
  {
    id: 6,
    title: "Cloud Computing AWS",
    academy: "Amazon Web Services",
    date: "2024",
    image: "/placeholder.svg?height=200&width=300",
    importance: "destacado",
  },
  {
    id: 7,
    title: "Node.js Backend",
    academy: "Backend Masters",
    date: "2023",
    image: "/placeholder.svg?height=200&width=300",
    importance: "intermedio",
  },
  {
    id: 8,
    title: "Docker Containers",
    academy: "DevOps Institute",
    date: "2024",
    image: "/placeholder.svg?height=200&width=300",
    importance: "complejo",
  },
  {
    id: 9,
    title: "Cybersecurity Basics",
    academy: "Security Academy",
    date: "2022",
    image: "/placeholder.svg?height=200&width=300",
    importance: "sencillo",
  },
];
