export const projects = [
  {
    id: 1,
    title: "E-Commerce Platform",
    complexity: "destacado",
    image: "/placeholder.svg?height=300&width=400",
    description: "Plataforma completa de comercio electrónico",
  },
  {
    id: 2,
    title: "Task Management App",
    complexity: "complejo",
    image: "/placeholder.svg?height=300&width=400",
    description: "Aplicación de gestión de tareas avanzada",
  },
  {
    id: 3,
    title: "Weather Dashboard",
    complexity: "intermedio",
    image: "/placeholder.svg?height=300&width=400",
    description: "Dashboard del clima con múltiples ciudades",
  },
  {
    id: 4,
    title: "Social Media App",
    complexity: "destacado",
    image: "/placeholder.svg?height=300&width=400",
    description: "Red social con chat en tiempo real",
  },
  {
    id: 5,
    title: "Inventory System",
    complexity: "complejo",
    image: "/placeholder.svg?height=300&width=400",
    description: "Sistema de inventario empresarial",
  },
  {
    id: 6,
    title: "Blog Platform",
    complexity: "intermedio",
    image: "/placeholder.svg?height=300&width=400",
    description: "Plataforma de blogs con CMS",
  },
  {
    id: 7,
    title: "AI Chatbot",
    complexity: "destacado",
    image: "/placeholder.svg?height=300&width=400",
    description: "Chatbot con inteligencia artificial",
  },
  {
    id: 8,
    title: "Portfolio Website",
    complexity: "sencillo",
    image: "/placeholder.svg?height=300&width=400",
    description: "Sitio web portfolio personal",
  },
  {
    id: 9,
    title: "Learning Platform",
    complexity: "complejo",
    image: "/placeholder.svg?height=300&width=400",
    description: "Plataforma de aprendizaje online",
  },
];
